In [ ]:
import pickle
import pandas as pd
from pathlib import Path
import zipfile

In [11]:
BASE_DIR = Path.cwd()
DATA_DIR = BASE_DIR.parents[1] / "project_data"

In [12]:
file_path_pkl = DATA_DIR / 'network_data.pkl'
with open(file_path_pkl, 'rb') as f: 
    G = pickle.load(f)

In [13]:
valid_users = set(G.nodes())
print(len(valid_users))

30005

In [14]:
def read_tsv_from_zip(zip_path, inner_name, columns=None):
    with zipfile.ZipFile(zip_path, "r") as z:
        with z.open(inner_name) as f:
            return pd.read_csv(
                f,
                sep="\t",              # FriendFeed 是 TSV
                names=columns,
                header=None if columns else "infer",
                na_values="\\N",
                engine="python",
                encoding="utf-8",
                on_bad_lines="skip"
            )

In [15]:
entries_cols = [
    "PostID",
    "PostedBy",
    "SourceName",
    "SourceURL",
    "GeoX",
    "GeoY",
    "Timestamp",
    "Text",
    "NumImg",
    "ImgURL",
    "NumVid",
    "VideoURL"
]

entries1 = read_tsv_from_zip(
    DATA_DIR / "entries1.zip",
    "entries1.csv",          # zip 里真实文件名
    columns=entries_cols
)

entries1.head()

,PostID,PostedBy,SourceName,SourceURL,GeoX,GeoY,Timestamp,Text,NumImg,ImgURL,NumVid,VideoURL
0,e/29af803d670fb8d67692095f3ee623e6,newsroom1,Ottawa Citizen - News,http://www.ottawacitizen.com/index.html,NaN,NaN,2010-08-02 18:43:10,RIM 'will not compromise' BlackBerry security ...,1,http://www.ottawacitizen.com/will+compromise+...,0,NaN
1,e/9c8413a376bec6389be4d46d0812c2bb,mehmetinnet,Mehmetin.Net,http://www.mehmetin.net,NaN,NaN,2010-08-02 19:15:52,Fethullah Gülen: Referandum siyasî olarak görü...,1,http://www.mehmetin.net/2010/08/fethullah-gul...,0,NaN
2,e/2d658d97842a466a9513f587f85b0e59,mehmetergin,Mehmetin.Net,http://www.mehmetin.net/,NaN,NaN,2010-08-02 19:15:52,Fethullah Gülen: Referandum siyasî olarak görü...,1,http://www.mehmetin.net/2010/08/fethullah-gul...,0,NaN
3,e/b269ab5d56be4e5e90c1954ecc1ef63a,afriki,NaN,NaN,NaN,NaN,2010-08-02 16:37:57,Мне тут недавно один дизайнер сказал: «Ну прот...,0,NaN,0,NaN
4,e/74f0a50c374a4ad6bddcbcc60c60cad9,hamsafar,NaN,NaN,NaN,NaN,2010-08-02 18:54:39,عرض سلام و خسته نباشيد:),0,NaN,0,NaN

In [16]:
entries2 = read_tsv_from_zip(
    DATA_DIR / "entries2.zip",
    "entries2.csv",          
    columns=entries_cols
)

entries2.head()

,PostID,PostedBy,SourceName,SourceURL,GeoX,GeoY,Timestamp,Text,NumImg,ImgURL,NumVid,VideoURL
0,e/4ec845b38287101deb6739d0fa64566d,starya,Lolcats 'n' Funny Pictures of Cats - I Can Has...,http://icanhascheezburger.com/,NaN,NaN,2010-08-24 20:00:38,"VIDEO: Kitteh Tricks - <a rel=""nofollow"" href=...",0,NaN,0,NaN
1,e/3ca878bcc2f5ed65c7217e4e8d1b6300,vkamutzki,Google Reader,http://www.google.com/reader/shared/0541245284...,NaN,NaN,2010-08-24 20:01:58,"Scene: Torontohenge Sunrise - <a rel=""nofollow...",0,NaN,0,NaN
2,e/19130fd6b5444f9ba321c58bdf7242a2,biznetsuk,HelloTxt,http://hellotxt.com/,NaN,NaN,2010-08-24 20:02:08,autobuynow.info/cars Car Buying: How to buy ne...,0,NaN,0,NaN
3,e/62945bae3a1433880c0a681081ee8cbb,monikap19,Books Nonfiction,http://bnmoon.blogspot.com/,NaN,NaN,2010-08-24 20:02:00,"Check Out Psychology for $89.28 - <a rel=""nofo...",0,NaN,0,NaN
4,e/41d2105e23fc70c1976387ab53f51c89,pendar,Google Reader,http://www.google.com/reader/shared/1316848039...,NaN,NaN,2010-08-24 20:02:07,رکورد گینس تایپ سریع پیام با استفاده از گوشی گ...,0,NaN,0,NaN

In [17]:
entries3 = read_tsv_from_zip(
    DATA_DIR / "entries3.zip",
    "entries3.csv",          
    columns=entries_cols
)

entries3.head()

,PostID,PostedBy,SourceName,SourceURL,GeoX,GeoY,Timestamp,Text,NumImg,ImgURL,NumVid,VideoURL
0,e/56dfd8c1beb24b52b33e5369a1004603,healthrockstar,Ping.fm,http://ping.fm/,NaN,NaN,2010-09-10 05:56:36,"HealthRockstar: weightloss,#fitness 11 News An...",0,NaN,0,NaN
1,e/6d231b54bd0289060de9be6905900961,aggregatore,Aggregatore di blog,http://aggregatore.seoguru.it,NaN,NaN,2010-09-10 05:30:00,Pop Star Coreana Cade Rovinosamente Sul Palco ...,0,NaN,0,NaN
2,e/4d38f93a832c4f1cb2e2446eb15e3888,afro2501,Ping.fm,http://ping.fm/,NaN,NaN,2010-09-10 05:56:36,"Interesting Page: Object moved <a rel=""nofollo...",0,NaN,0,NaN
3,e/0e38d17bf5a47b55ae5782c8a6d985bc,cleanthinking,Cleanthinking.de - Cleantech und Energie News,http://www.cleanthinking.de/,NaN,NaN,2010-09-10 05:56:24,"Hintergrund Geothermie: Die Quelle, die nie ve...",0,NaN,0,NaN
4,e/5cb0fbb41a0567b2e3f228d0d6cec52e,gnomebeatz,Twitter,http://twitter.com/questlove/statuses/24081170630,NaN,NaN,2010-09-10 05:56:36,"@<a rel=""nofollow"" href=""http://twitter.com/ma...",0,NaN,0,NaN

In [18]:
entries1_sub = entries1[entries1["PostedBy"].isin(valid_users)].copy()
entries2_sub = entries2[entries2["PostedBy"].isin(valid_users)].copy()
entries3_sub = entries3[entries3["PostedBy"].isin(valid_users)].copy()
entires_sub = pd.concat([entries1_sub, entries2_sub, entries3_sub], ignore_index=True)

In [19]:
entires_sub.shape

(3014561, 12)

In [20]:
import re
import html

def clean_text(text):
    if not isinstance(text, str) or text.strip() == "":
        return ""

    # 1) 删除 <a>...</a>（你原写法有个空格：</a >，我这里修正为 </a>）
    text = re.sub(r"<a.*?>.*?</a>", "", text, flags=re.DOTALL | re.IGNORECASE)

    # 2) 干掉其他 HTML 标签
    text = re.sub(r"<.*?>", "", text)

    # 3) 转换 HTML 实体 (如 &amp; -> &)
    text = html.unescape(text)

    # 4) 删除 URL
    text = re.sub(r"(https?://\S+|www\.\S+)", "", text)

    # 5) 删除 RT 转发块（保守写法：避免误删太多）
    text = re.sub(r"RT\s*@.*?:.*?(?= - |$)", "", text, flags=re.IGNORECASE)

    # 6) 删除 via 来源和 @用户名
    text = re.sub(r"via\s*@\S+", "", text, flags=re.IGNORECASE)
    text = re.sub(r"@\w+", "", text)

    # 7) 清理多余空格
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [22]:
from langdetect import detect

def is_english(text):
    if not isinstance(text, str) or len(text) < 10:
        return False
    try:
        return detect(text) == "en"
    except:
        return False

In [21]:
entires_sub['cleaned_text'] = entires_sub['Text'].apply(clean_text)
entires_sub['cleaned_text'].sample(5).to_list()

['10 Pack of Universal Generation X Cell Phone Antenna Booster Signal Enhancers By Michael Benaudis Newspaper',
 'Wie schützt man eigentlich seine Daten auf dem SmartPhone? -',
 'As you read the report you’ll discover this un-tapped real estate vehicle. It’s so unknown Kenny and his students are having a field day snapping up bargains, and barely scratching the surface of what’s available on the market.',
 "Air Force May Boot Decorated Combat Pilot Who Also Happens to Be Gay [Don't Ask Don't Tell] -",
 'new kindle book: The Girls at Mount Morris - by Amanda Minnie Douglas.']

In [ ]:
entries_filter = entires_sub[entires_sub["cleaned_text"].str.len() >= 10]
entries_filter.shape

(2890881, 13)

In [ ]:
# a = entries_filter.head(10000)
# entries1_en = a[a["cleaned_text"].apply(is_english)].copy()
# entries1_en.shape

(4530, 13)

In [28]:
entries1_en = entries_filter[entries_filter["cleaned_text"].apply(is_english)].copy()
entries1_en.shape

(1738892, 13)

In [29]:
entries1_en.head(5)

,PostID,PostedBy,SourceName,SourceURL,GeoX,GeoY,Timestamp,Text,NumImg,ImgURL,NumVid,VideoURL,cleaned_text
0,e/29af803d670fb8d67692095f3ee623e6,newsroom1,Ottawa Citizen - News,http://www.ottawacitizen.com/index.html,NaN,NaN,2010-08-02 18:43:10,RIM 'will not compromise' BlackBerry security ...,1,http://www.ottawacitizen.com/will+compromise+...,0,NaN,RIM 'will not compromise' BlackBerry security ...
7,e/36cfd2743b8a4385a374f79fcac358dd,robfelty,Bookmarklet,http://friendfeed.com/share/bookmarklet,NaN,NaN,2010-08-02 19:15:56,Undersea river discovered flowing on sea bed -...,1,http://www.telegraph.co.uk/earth/environment/...,0,NaN,Undersea river discovered flowing on sea bed -...
9,e/7dd779c201dbe9a9d2a97302cbf3640b,moonboy,Tumblr,http://silverpi.tumblr.com/,NaN,NaN,2010-08-02 16:56:42,"The Ministry of Silly Walks - <a rel=""nofollow...",1,http://silverpi.tumblr.com/post/893789572,0,NaN,The Ministry of Silly Walks -
12,e/e1f39199b774a2f6f30e1caa4153061c,senaysen,YouTube favorites,http://www.youtube.com/profile?user=3yasindagi...,NaN,NaN,2010-08-02 19:12:38,Lady Gaga - Bad Romance - live cover - Lissie ...,0,NaN,1,http://www.youtube.com/watch?v=MWe07krS8_E&fe...,Lady Gaga - Bad Romance - live cover - Lissie -
23,e/52c64f21d2944d4ca76b7566bec032bd,biteme,NaN,NaN,NaN,NaN,2010-08-02 18:58:02,War is stupid.,0,NaN,0,NaN,War is stupid.

In [30]:
out_path  = DATA_DIR / 'entries1_en.jsonl'

entries1_en.to_json(
    out_path,
    orient="records",
    lines=True,
    force_ascii=False
)

In [31]:
import pandas as pd

entries1_en = pd.read_json(
    out_path,
    orient="records",
    lines=True
)

In [32]:
entries1_en.head(3)

,PostID,PostedBy,SourceName,SourceURL,GeoX,GeoY,Timestamp,Text,NumImg,ImgURL,NumVid,VideoURL,cleaned_text
0,e/29af803d670fb8d67692095f3ee623e6,newsroom1,Ottawa Citizen - News,http://www.ottawacitizen.com/index.html,NaN,NaN,2010-08-02 18:43:10,RIM 'will not compromise' BlackBerry security ...,1,http://www.ottawacitizen.com/will+compromise+...,0,None,RIM 'will not compromise' BlackBerry security ...
1,e/36cfd2743b8a4385a374f79fcac358dd,robfelty,Bookmarklet,http://friendfeed.com/share/bookmarklet,NaN,NaN,2010-08-02 19:15:56,Undersea river discovered flowing on sea bed -...,1,http://www.telegraph.co.uk/earth/environment/...,0,None,Undersea river discovered flowing on sea bed -...
2,e/7dd779c201dbe9a9d2a97302cbf3640b,moonboy,Tumblr,http://silverpi.tumblr.com/,NaN,NaN,2010-08-02 16:56:42,"The Ministry of Silly Walks - <a rel=""nofollow...",1,http://silverpi.tumblr.com/post/893789572,0,None,The Ministry of Silly Walks -

In [35]:
import pandas as pd

df_path  = DATA_DIR / 'entries1_en.zip'

df = pd.read_json(
    df_path,   
    orient="records",
    lines=True,
    compression="zip"
)

In [36]:
df.head()

,PostID,PostedBy,SourceName,SourceURL,GeoX,GeoY,Timestamp,Text,NumImg,ImgURL,NumVid,VideoURL,cleaned_text
0,e/29af803d670fb8d67692095f3ee623e6,newsroom1,Ottawa Citizen - News,http://www.ottawacitizen.com/index.html,NaN,NaN,2010-08-02 18:43:10,RIM 'will not compromise' BlackBerry security ...,1,http://www.ottawacitizen.com/will+compromise+...,0,None,RIM 'will not compromise' BlackBerry security ...
1,e/36cfd2743b8a4385a374f79fcac358dd,robfelty,Bookmarklet,http://friendfeed.com/share/bookmarklet,NaN,NaN,2010-08-02 19:15:56,Undersea river discovered flowing on sea bed -...,1,http://www.telegraph.co.uk/earth/environment/...,0,None,Undersea river discovered flowing on sea bed -...
2,e/7dd779c201dbe9a9d2a97302cbf3640b,moonboy,Tumblr,http://silverpi.tumblr.com/,NaN,NaN,2010-08-02 16:56:42,"The Ministry of Silly Walks - <a rel=""nofollow...",1,http://silverpi.tumblr.com/post/893789572,0,None,The Ministry of Silly Walks -
3,e/e1f39199b774a2f6f30e1caa4153061c,senaysen,YouTube favorites,http://www.youtube.com/profile?user=3yasindagi...,NaN,NaN,2010-08-02 19:12:38,Lady Gaga - Bad Romance - live cover - Lissie ...,0,None,1,http://www.youtube.com/watch?v=MWe07krS8_E&fe...,Lady Gaga - Bad Romance - live cover - Lissie -
4,e/52c64f21d2944d4ca76b7566bec032bd,biteme,None,None,NaN,NaN,2010-08-02 18:58:02,War is stupid.,0,None,0,None,War is stupid.

In [37]:
df.shape

(1738892, 13)

In [ ]:
comments_cols = [
    "PostID",
    "EntryID",
    "PostedBy",
    "SourceName",
    "SourceURL",
    "GeoX",
    "GeoY",
    "Timestamp",
    "Text",
    "NumImg",
    "ImgURL",
    "NumVid",
    "VideoURL",
]

comments = read_tsv_from_zip(
    DATA_DIR / "comments.zip",
    "commentAugSept.csv",          # zip 里真实文件名
    columns=comments_cols
)